title: "BogoBogo"
theme: "just-the-docs"

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2122S1-CS2103-F10-2/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
